// Automated attack launcher: replicates TW's two-step (confirm + command) AJAX flow.

/**
 * Launches an attack automatically.
 * Explaining the two-step AJAX process used by TribalWars to prevent botting.
 * * @param {Object} units - Object containing unit counts { spear: 10, ... }
 * @param {string|number} targetId - Internal database ID of the target village
 * @param {string} [coordsOverride] - Optional "x|y" target coords; when provided, skips reading
 *   TWMap.context._curFocus (needed on pages with no live map, e.g. the Farm Assistant list).
 */
async function launchAttack(units, targetId, coordsOverride) {
    try {
        const GD = typeof unsafeWindow !== 'undefined' ? unsafeWindow.game_data : window.game_data;
        if (!GD || !GD.csrf) throw new Error(t('core.errorGameDataNotFound'));

        const csrfToken = GD.csrf;
        const currentVillage = GD.village.id;
        const baseUrl = `https://${window.location.host}/game.php?village=${currentVillage}&screen=place`;

        /**
         * AJAX CALL #1: THE PREPARATION PHASE (ajax=confirm)
         * * PURPOSE: This call asks the server to validate the attack. 
         * The server checks if you have enough troops and if the target is valid.
         * * WHY IT'S NECESSARY: The server does not launch the attack yet. 
         * Instead, it returns a JSON object containing the "Confirmation Dialog" HTML.
         * This HTML contains the unique security tokens (ch and honeypot) required for Step 2.
         */
        console.log("Step 1: Requesting confirmation dialog...");

        let coordX = "", coordY = "";
        if (coordsOverride) {
            [coordX, coordY] = coordsOverride.split('|');
        } else {
            const rawFocus = unsafeWindow.TWMap.context._curFocus;
            if (rawFocus) {
                const focusStr = rawFocus.toString();
                coordX = focusStr.substring(0, 3);
                coordY = focusStr.substring(3, 6);
            }
        }

        const step1Data = new URLSearchParams();
        step1Data.append("target", targetId);
        step1Data.append("x", coordX);
        step1Data.append("y", coordY);
        step1Data.append("attack", "1"); // In PT servers, the button internal value is "Atacar" (try for now with 1)
        step1Data.append("h", csrfToken);

        for (const [unit, amount] of Object.entries(units)) {
            step1Data.append(unit, amount);
        }

        const responseStep1 = await fetch(`${baseUrl}&ajax=confirm`, {
            method: "POST",
            body: step1Data,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
                'TribalWars-Ajax': '1' // Tells the server to return JSON instead of a full page redirect
            }
        });

        const jsonResponse = await responseStep1.json();

        // Check for server-side logic errors (e.g., "Not enough units")
        if (jsonResponse.error) {
            const msg = Array.isArray(jsonResponse.error) ? jsonResponse.error[0] : jsonResponse.error;
            throw new Error(msg);
        }

        // The dialog HTML is stored in response.dialog
        const htmlText = jsonResponse.response.dialog;
        const parser = new DOMParser();
        const doc = parser.parseFromString(htmlText, "text/html");

        /**
         * TOKEN EXTRACTION (The "Secret Sauce")
         * * 'ch': Confirmation Hash. A one-time code generated by the server for this specific attack.
         * 'dynamicInput': A hidden field with a randomized name (e.g. "8219ab..."). 
         * This is a "honeypot" protection; if you don't send this exact name/value pair in Step 2, 
         * the server knows you are a bot and returns "Invalid Command".
         */
        const chInput = doc.querySelector('input[name="ch"]');
        const dynamicInput = doc.querySelector('input[type="hidden"]:not([name="ch"]):not([name="template_id"]):not([name="source_village"])');

        if (!chInput || !dynamicInput) {
            throw new Error(t('core.errorSecurityTokensMissing'));
        }

        /**
         * AJAX CALL #2: THE EXECUTION PHASE (action=command)
         * * PURPOSE: This is the actual "Confirm" click. It sends the troops out.
         * * WHY IT'S NECESSARY: You must prove to the server that you performed Step 1 
         * by providing the 'ch' hash and the dynamic honeypot token.
         */
        console.log(`Step 2: Executing attack with hash: ${chInput.value}`);

        const step2Data = new URLSearchParams();
        step2Data.append(dynamicInput.name, dynamicInput.value); // Sending the dynamic honeypot
        step2Data.append("ch", chInput.value);                  // Sending the confirmation hash
        step2Data.append("x", coordX);
        step2Data.append("y", coordY);
        step2Data.append("action", "command");                  // The action that actually triggers the movement
        step2Data.append("h", csrfToken);

        for (const [unit, amount] of Object.entries(units)) {
            step2Data.append(unit, amount);
        }

        const responseStep2 = await fetch(`${baseUrl}&action=command&h=${csrfToken}`, {
            method: "POST",
            body: step2Data,
            headers: { 'Content-Type': 'application/x-www-form-urlencoded' }
        });

        if (responseStep2.ok) {
            const successMsg = t('core.attackSent', { coords: coordX + '|' + coordY });
            showAutoHideBox(successMsg, false);
            console.log("%c " + successMsg, "color: green; font-weight: bold;");
            return true;
        } else {
            throw new Error(t('core.errorServerRejectedCommand'));
        }

    } catch (error) {
        if (typeof showAutoHideBox === 'function') {
            showAutoHideBox(error.message, true);
        }
        console.error("Attack Failed:", error.message);
        return false;
    }
}
